# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Karabingen < Formula
  desc "CLI tool to generate karabiner.json file from simplified YAML"
  homepage "https://github.com/fgazat/karabingen"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fgazat/karabingen/releases/download/v0.1.2/karabingen_Darwin_x86_64.tar.gz"
      sha256 "64cc7e00274a014eb5d0871fed636aaffb0d4b050087cdcc58fc428a59f30622"

      def install
        bin.install "karabingen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fgazat/karabingen/releases/download/v0.1.2/karabingen_Darwin_arm64.tar.gz"
      sha256 "c6cf910c0823e331f48171efb7a2f2d4f40e867cf20db81629ec5618998e0f8d"

      def install
        bin.install "karabingen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgazat/karabingen/releases/download/v0.1.2/karabingen_Linux_x86_64.tar.gz"
      sha256 "76167f4ee274838d194be813a812c384bc17ea83df8e7923a5ddf20f86079896"
      def install
        bin.install "karabingen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fgazat/karabingen/releases/download/v0.1.2/karabingen_Linux_arm64.tar.gz"
      sha256 "0b14fe29c7018b523d8557761cc6329d2fbff6df824ed1c1a485bc7ba91fdb96"
      def install
        bin.install "karabingen"
      end
    end
  end

  test do
    system "#{bin}/karabingen", "--help"
  end
end
